### ISSUE TITLE
Adding the prompt?

### ISSUE THREAD

**Issue by siennathesane** [blimmer/zsh-aws-vault#13]
How do you add the prompt to the agnoster theme? I was reading through the agnoster documentation and I was unable to figure it out.

**Comment by blimmer** [comment]
Hey @mxplusb - did you check out the README https://github.com/blimmer/zsh-aws-vault#prompt-segment ? There's some sample code in there. If you did check that out and it isn't clear, let me know and I'll try to improve the docs.

Let me know! Thanks

**Comment by sibrahim001982** [comment]
Hi @blimmer 

I have to be honest with you, I read what you wrote and couldn't get the prompt to work!

**Comment by sibrahim001982** [comment]
@mxplusb You managed to add the prompt?

**Comment by blimmer** [comment]
Hey @sibrahim001982 - I added more detail to the README. Does that help? Adding to the prompt will vary depending on the oh-my-zsh theme you use. I linked to my custom agnoster theme file as an example. Hope that helps!

**Comment by siennathesane** [comment]
I'm not using AWS anymore, so no more aws-vault, sorry!

**Comment by blimmer** [comment]
OK, no problem. I'll go ahead and close this issue.
