### ISSUE TITLE
Merge reegnz/aws-vault-zsh-plugin zsh completion script

### ISSUE THREAD

**Issue by reegnz** [blimmer/zsh-aws-vault#20]
Would you be open to merging [my aws-vault completion script](https://github.com/reegnz/aws-vault-zsh-plugin)? I'd be glad to have that in a plugin that's more popular than mine, so that other people benefit from it as well. :)

**Comment by blimmer** [comment]
Hey @reegnz - sure, I'd be happy to accept a PR to improve auto-completion for this plugin!
