### ISSUE TITLE
Latest version opens chrome window that is not maximized

### ISSUE THREAD

**Issue by 1oglop1** [blimmer/zsh-aws-vault#28]
Hi, thank you for this amazing project.
After updating to the latest version the new browser window is not maximized anymore.
`avli <profile>` - now opened a chrome window that is not maximized and the content is squeezed.

Also calling `avli` now makes the terminal "blink" for a few seconds.

I believe this commit introduced the problem:
https://github.com/blimmer/zsh-aws-vault/commit/7b1b5db790bb2520b2a6f91ba3233809ed5c2521

As well as another problem (that was there before)
The `--path` argument is not respected with `avli`, it works perfectly with `avl`.
`avli <profile> --path=lambda` -> leads to the main console page.

`google-chrome --incognito $(avl -s infra-tools-dev --path="lambda")` - works as expected -> starts maximized window and goes to `lambda` page.

## Workarounds
* `--path` - I applied a workaround by modifying `function avli()` on L45 to `login_url="$(avll $*)"`
* blinking terminal -- I modified L82 to `(${browser} --no-first-run --incognito "${login_url}" 1>/dev/null 2>/dev/null && rm -rf "${AVLI_TMP_PROFILE}")`

**Comment by blimmer** [comment]
Hey @1oglop1 - thanks for the kind words and for reporting these issues.

For the extra arguments (e.g., `path`), this definitely makes sense. I opened #29 which updates all functions to pass through extra arguments. Please have a look and see if it fixes the problem.

For the un-maximized window, that makes sense based on the changes made in #26 (specifically the removal of the `--start-maximized` flag. The reason the command you ran (`google-chrome --incognito`) worked is that it's using the preferences from your default Chrome installation. `avli` creates a brand new profile specific to the session you're running. That way, you can `avli` into multiple different profiles at once. By just using `--incognito`, you would only be able to log into a single profile with `avli` at once.

I don't think I want to choose for the user what preferences are passed to their `avli` browser session. So, maybe the best option is to introduce a way to pass arbitrary flags to the browser startup. Then, if you want to `--start-maximized`, you can but others don't have to if they don't want to. What do you think?

**Comment by 1oglop1** [comment]
I did not do enough testing with `--icognito`.. I just tried to make things work ... today I found out it does not work as expected and a brand new profile is needed. 

I'm in favour of the configuration option!
What would be the entry point for this config? Env var or a value in config file of the plugin? (both work for me)

something like `ZSH_AWS_VAULT_BROWSER_OPTIONS` - bit long but descriptive, maybe there is a convention for omz plugins

PS I tried the fix from #29 and it works!

**Comment by blimmer** [comment]
Sounds good - I merged #29.

For the browser options, I think we should call it `AWS_VAULT_PL_BROWSER_OPTS` to keep with the convention for selecting a browser (`AWS_VAULT_PL_BROWSER`) https://github.com/blimmer/zsh-aws-vault#avli.

I'll likely have time this weekend to have a look but, if you're interested in submitting a PR before then, please feel free!
