### ISSUE TITLE
Remove qoutes from browser option var

### ISSUE THREAD

**Issue by farhansaed** [blimmer/zsh-aws-vault#31]
Hi please remove qoutes from browser option vars specifically for firefox
If not then when firefox private windows opens up with two tabs one containing aws console and other one displaying all your file / directories in local drive @ following URL `file:///Users/myusername/`

`"$AWS_VAULT_PL_BROWSER_LAUNCH_OPTS"` should be updated with `$AWS_VAULT_PL_BROWSER_LAUNCH_OPTS`

**Comment by blimmer** [comment]
Hi @farhansaed - thank you for reporting this issue. I'm currently away from a laptop to confirm/fix this. Would you please submit a PR? I'll be happy to merge it.

**Comment by farhansaed** [comment]
I have generated the pull request.
